# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto_trials/PlatformRegisterReq.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'proto_trials/PlatformRegisterReq.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&proto_trials/PlatformRegisterReq.proto\x12\x05proto\"\xa5\x03\n\x13PlatformRegisterReq\x12\x10\n\x08nickname\x18\x01 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x02 \x01(\t\x12\x0f\n\x07open_id\x18\x03 \x01(\t\x12\x0e\n\x06region\x18\x04 \x01(\t\x12\x11\n\tavatar_id\x18\x05 \x01(\r\x12\x15\n\rplatform_type\x18\x06 \x01(\r\x12\x17\n\x0fplatform_sdk_id\x18\x07 \x01(\r\x12,\n\x06source\x18\x08 \x01(\x0e\x32\x1c.proto.EAccount_DownloadType\x12\x1b\n\x13\x65\x64itor_register_key\x18\t \x01(\t\x12\x33\n\rnewbie_choice\x18\n \x01(\x0e\x32\x1c.proto.EAccount_NewbieChoice\x12\x1e\n\x16platform_register_info\x18\x0b \x01(\x0c\x12\x10\n\x08language\x18\x0c \x01(\t\x12\x36\n\rusing_version\x18\r \x01(\x0e\x32\x1f.proto.EAuth_ClientUsingVersion\x12\x18\n\x10is_newbie_choice\x18\x0e \x01(\x08*\xae\x01\n\x15\x45\x41\x63\x63ount_DownloadType\x12\x15\n\x11\x44ownloadType_NONE\x10\x00\x12\x1c\n\x18\x44ownloadType_INSTANTGAME\x10\x01\x12\x14\n\x10\x44ownloadType_IOS\x10\x02\x12\x17\n\x13\x44ownloadType_HUAWEI\x10\x03\x12\x17\n\x13\x44ownloadType_XIAOMI\x10\x04\x12\x18\n\x14\x44ownloadType_SAMSUNG\x10\x05*\xa1\x01\n\x15\x45\x41\x63\x63ount_NewbieChoice\x12\x15\n\x11NewbieChoice_NONE\x10\x00\x12\x1b\n\x17NewbieChoice_NEW_PLAYER\x10\x01\x12\x1b\n\x17NewbieChoice_FPS_PLAYER\x10\x02\x12\x18\n\x14NewbieChoice_VETERAN\x10\x03\x12\x1d\n\x19NewbieChoice_NEEDMOREINFO\x10\x63*\xae\x01\n\x18\x45\x41uth_ClientUsingVersion\x12\x1b\n\x17\x43lientUsingVersion_NONE\x10\x00\x12\x1d\n\x19\x43lientUsingVersion_NORMAL\x10\x01\x12\x1a\n\x16\x43lientUsingVersion_MAX\x10\x02\x12\x1a\n\x16\x43lientUsingVersion_FFI\x10\x03\x12\x1e\n\x1a\x43lientUsingVersion_MAX_HPE\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_trials.PlatformRegisterReq_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EACCOUNT_DOWNLOADTYPE']._serialized_start=474
  _globals['_EACCOUNT_DOWNLOADTYPE']._serialized_end=648
  _globals['_EACCOUNT_NEWBIECHOICE']._serialized_start=651
  _globals['_EACCOUNT_NEWBIECHOICE']._serialized_end=812
  _globals['_EAUTH_CLIENTUSINGVERSION']._serialized_start=815
  _globals['_EAUTH_CLIENTUSINGVERSION']._serialized_end=989
  _globals['_PLATFORMREGISTERREQ']._serialized_start=50
  _globals['_PLATFORMREGISTERREQ']._serialized_end=471
# @@protoc_insertion_point(module_scope)
